// client-3d/src/constants/archetypeStarterNodes.ts

// NOTE: 
// The 'symbol' names below are from the new diversified list. The frontend might need
// corresponding image assets (e.g., Ankh.svg, Mandala.svg) or a way to display these
// symbol names textually if visual assets are not yet available.
// The 'concept' and 'thinker' names are drawn from the existing seed_concepts_llm_generated.json (approx 85 entries).

export const archetypeStarterNodes: Record<string, { concept: string; symbol: string; thinker: string }> = {
  "The Auric Messenger":           { "concept": "Information",             "symbol": "Ouroboros",        "thinker": "Alan Turing" },
  "The Moonlit Sage":              { "concept": "Consciousness",           "symbol": "Ankh",             "thinker": "Carl Jung" },
  "The Nightblade":                { "concept": "Shadow (Jungian Concept)", "symbol": "Mandala",          "thinker": "Plato" },
  "The Reflective Chalice":        { "concept": "Self",                    "symbol": "Yin-Yang",         "thinker": "Isaac Newton" },
  "The Shadow Scholar":            { "concept": "Collective Unconscious",  "symbol": "Tree of Life",     "thinker": "Albert Einstein" },
  "The Mystic Crucible":           { "concept": "Paradox",                 "symbol": "Lotus Flower",     "thinker": "Charles Darwin" },
  "The Nurturing Oracle":          { "concept": "Ecosystem",               "symbol": "Pentagram",        "thinker": "Marie Curie" },
  "The Devoted Protector":         { "concept": "Order",                   "symbol": "Spiral",           "thinker": "Adam Smith" },
  "The Gentle Vessel":             { "concept": "Humanism",                "symbol": "Labyrinth",        "thinker": "Leonardo da Vinci" },
  "The Melancholic Lover":         { "concept": "Grief",                   "symbol": "Eye of Horus",     "thinker": "William Shakespeare" },
  "The Passionate Dreamer":        { "concept": "Narrative",               "symbol": "Flower of Life",   "thinker": "Alan Turing" },
  "The Visionary Defender":        { "concept": "Democracy",               "symbol": "Triangle",         "thinker": "Carl Jung" },
  "The Keeper of Tides":           { "concept": "Time",                    "symbol": "Infinity Symbol",  "thinker": "Plato" },
  "The Hermit Prophet":            { "concept": "Non-Duality",             "symbol": "Chakras",          "thinker": "Isaac Newton" },
  "The Lunar Alchemist":           { "concept": "Emergence",               "symbol": "Caduceus",         "thinker": "Albert Einstein" },
  "The Midnight Guardian":         { "concept": "Cybersecurity",           "symbol": "Phoenix",          "thinker": "Charles Darwin" },
  "The Silent Sentinel":           { "concept": "Mind",                    "symbol": "Circle",           "thinker": "Marie Curie" },
  "The Witchblade":                { "concept": "Power",                   "symbol": "Hourglass",        "thinker": "Adam Smith" },
  "The Moonlit Anchor":            { "concept": "Determinism",             "symbol": "Cube",             "thinker": "Leonardo da Vinci" },
  "The Dream Vessel":              { "concept": "Illusion",                "symbol": "Mirror",           "thinker": "William Shakespeare" },
  "The Dark Crucible":             { "concept": "Chaos",                   "symbol": "Ouroboros",        "thinker": "Alan Turing" },
  "The Defender of Order":         { "concept": "System",                  "symbol": "Ankh",             "thinker": "Carl Jung" },
  "The Just Warrior":              { "concept": "Freedom (Free Will)",     "symbol": "Mandala",          "thinker": "Plato" },
  "The Zealous Crusader":          { "concept": "Truth",                   "symbol": "Yin-Yang",         "thinker": "Isaac Newton" },
  "The Stoic Guardian":            { "concept": "Stoicism",                "symbol": "Tree of Life",     "thinker": "Albert Einstein" },
  "The Blooded Vessel":            { "concept": "Evolution",               "symbol": "Lotus Flower",     "thinker": "Charles Darwin" },
  "The Iron Crucible":             { "concept": "Matter",                  "symbol": "Pentagram",        "thinker": "Marie Curie" },
  "The Keeper of Lore":            { "concept": "Information",             "symbol": "Spiral",           "thinker": "Adam Smith" },
  "The Wise Architect":            { "concept": "Pattern",                 "symbol": "Labyrinth",        "thinker": "Leonardo da Vinci" },
  "The Visionary Alchemist":       { "concept": "AI (Artificial Intelligence)", "symbol": "Eye of Horus", "thinker": "William Shakespeare" },
  "The Tactical Herald":           { "concept": "Algorithm",               "symbol": "Flower of Life",   "thinker": "Alan Turing" },
  "The Protean Guard":             { "concept": "Complexity",              "symbol": "Triangle",         "thinker": "Carl Jung" },
  "The Iron Messenger":            { "concept": "Network",                 "symbol": "Infinity Symbol",  "thinker": "Plato" },
  "The Fiery Magus":               { "concept": "Power",                   "symbol": "Chakras",          "thinker": "Isaac Newton" },
  "The Silent Scribe":             { "concept": "Narrative",               "symbol": "Caduceus",         "thinker": "Albert Einstein" },
  "The Living Talisman":           { "concept": "Archetype (General Concept)", "symbol": "Phoenix",      "thinker": "Charles Darwin" },
  "The Secret Fire":               { "concept": "Renaissance",             "symbol": "Circle",           "thinker": "Marie Curie" },
  "The Diplomatic Sage":           { "concept": "Capitalism",              "symbol": "Hourglass",        "thinker": "Adam Smith" },
  "The Charming Duelist":          { "concept": "Market (Economics)",      "symbol": "Cube",             "thinker": "Leonardo da Vinci" },
  "The Artful Vessel":             { "concept": "Impressionism",           "symbol": "Mirror",           "thinker": "William Shakespeare" },
  "The Cunning Mediator":          { "concept": "Blockchain",              "symbol": "Ouroboros",        "thinker": "Alan Turing" },
  "The Creative Trickster":        { "concept": "Paradox",                 "symbol": "Ankh",             "thinker": "Carl Jung" },
  "The Crucible Stone":            { "concept": "Being",                   "symbol": "Mandala",          "thinker": "Plato" },
  "The Conquering Visionary":      { "concept": "System",                  "symbol": "Yin-Yang",         "thinker": "Isaac Newton" },
  "The Steward of Plenty":         { "concept": "Computation",             "symbol": "Tree of Life",     "thinker": "Albert Einstein" },
  "The Judicious Patriarch":       { "concept": "Scientific Method",       "symbol": "Lotus Flower",     "thinker": "Charles Darwin" },
  "The Prophetic Flame":           { "concept": "Observer Effect",         "symbol": "Pentagram",        "thinker": "Marie Curie" },
  "The Enlightened Monarch":       { "concept": "Decentralization",        "symbol": "Spiral",           "thinker": "Adam Smith" },
  "The Sunlit Warrior":            { "concept": "DNA (Deoxyribonucleic Acid)", "symbol": "Labyrinth",    "thinker": "Leonardo da Vinci" },
  "The Philosopher‑King":          { "concept": "Ego",                     "symbol": "Eye of Horus",     "thinker": "William Shakespeare" },
  "The Illuminated Vessel":        { "concept": "Non-Being",               "symbol": "Flower of Life",   "thinker": "Alan Turing" },
  "The Stoic Luminary":            { "concept": "General Relativity",      "symbol": "Triangle",         "thinker": "Carl Jung" },
  "The Golden Alchemist":          { "concept": "The Absolute",            "symbol": "Infinity Symbol",  "thinker": "Plato" },
  "The Radiant Consort":           { "concept": "Duality",                 "symbol": "Chakras",          "thinker": "Isaac Newton" },
  "The Guardian of Light":         { "concept": "Spacetime",               "symbol": "Caduceus",         "thinker": "Albert Einstein" },
  "The Iron Sovereign":            { "concept": "Big Bang Theory",         "symbol": "Phoenix",          "thinker": "Charles Darwin" },
  "The Fiery Crusader":            { "concept": "Natural Selection",       "symbol": "Circle",           "thinker": "Marie Curie" },
  "The Visionary Herald":          { "concept": "Machine Learning",        "symbol": "Hourglass",        "thinker": "Adam Smith" },
  "The Brilliant Strategist":      { "concept": "Biotechnology",           "symbol": "Cube",             "thinker": "Leonardo da Vinci" },
  "The Luminous Scribe":           { "concept": "Internet",                "symbol": "Mirror",           "thinker": "William Shakespeare" },
  "The Disciplined Magician":      { "concept": "Buddhism",                "symbol": "Ouroboros",        "thinker": "Alan Turing" },
  "The Radiant Transmuter":        { "concept": "Entropy",                 "symbol": "Ankh",             "thinker": "Carl Jung" },
  "The Charismatic Magus":         { "concept": "Quantum Entanglement",    "symbol": "Mandala",          "thinker": "Plato" },
  "The Resolute Pillar":           { "concept": "Causality",               "symbol": "Yin-Yang",         "thinker": "Isaac Newton" },
  "The Embodied Fire":             { "concept": "Anxiety",                 "symbol": "Tree of Life",     "thinker": "Albert Einstein" },
  "The Purifying Sun":             { "concept": "Reality",                 "symbol": "Lotus Flower",     "thinker": "Charles Darwin" },
  "The Benevolent Ruler":          { "concept": "Existence",               "symbol": "Pentagram",        "thinker": "Marie Curie" },
  "The Passionate Hero":           { "concept": "Hero's Journey",          "symbol": "Spiral",           "thinker": "Adam Smith" },
  "The Loving Chalice":            { "concept": "Trauma",                  "symbol": "Labyrinth",        "thinker": "Leonardo da Vinci" },
  "The Tempered Lover":            { "concept": "Space",                   "symbol": "Eye of Horus",     "thinker": "William Shakespeare" },
  "The Creative Catalyst":         { "concept": "Mind",                    "symbol": "Flower of Life",   "thinker": "Alan Turing" },
  "The Crusading Lover":           { "concept": "Self",                    "symbol": "Triangle",         "thinker": "Carl Jung" },
  "The Harvest Maiden":            { "concept": "Information",             "symbol": "Infinity Symbol",  "thinker": "Plato" },
  "The Gracious Matriarch":        { "concept": "AI (Artificial Intelligence)", "symbol": "Chakras",   "thinker": "Isaac Newton" },
  "The Blooming Oracle":           { "concept": "Order",                   "symbol": "Caduceus",         "thinker": "Albert Einstein" },
  "The Heartbound Shield":         { "concept": "System",                  "symbol": "Phoenix",          "thinker": "Charles Darwin" },
  "The Loyal Commander":           { "concept": "Complexity",              "symbol": "Circle",           "thinker": "Marie Curie" },
  "The Passion Spark":             { "concept": "Time",                    "symbol": "Hourglass",        "thinker": "Adam Smith" },
  "The Enduring Heart":            { "concept": "Network",                 "symbol": "Cube",             "thinker": "Leonardo da Vinci" },
  "The Embodied Grace":            { "concept": "Illusion",                "symbol": "Mirror",           "thinker": "William Shakespeare" },
  "The Tempered Flame":            { "concept": "Chaos",                   "symbol": "Ouroboros",        "thinker": "Alan Turing" },
  "The Pillar of Wisdom":          { "concept": "Consciousness",           "symbol": "Ankh",             "thinker": "Carl Jung" },
  "The Sacred Fountain":           { "concept": "Truth",                   "symbol": "Mandala",          "thinker": "Plato" },
  "The Alchemical Judge":          { "concept": "Paradox",                 "symbol": "Yin-Yang",         "thinker": "Isaac Newton" }
};