export const archetypeStarterNodes: Record<string, { concept: string; symbol: string; thinker: string }> = {
  "The Auric Messenger":           { "concept": "Communication",          "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Moonlit Sage":              { "concept": "Being",                   "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Nightblade":                { "concept": "Non-Being",               "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Reflective Chalice":        { "concept": "Existence",               "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Shadow Scholar":            { "concept": "Consciousness",           "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Mystic Crucible":           { "concept": "Mind",                    "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Nurturing Oracle":          { "concept": "Matter",                  "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Devoted Protector":         { "concept": "Causality",               "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Gentle Vessel":             { "concept": "Time",                    "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Melancholic Lover":         { "concept": "Space",                   "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Passionate Dreamer":        { "concept": "Truth",                   "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Visionary Defender":        { "concept": "Reality",                 "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Keeper of Tides":           { "concept": "Illusion",                "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Hermit Prophet":            { "concept": "Freedom (Free Will)",     "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Lunar Alchemist":           { "concept": "Determinism",             "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Midnight Guardian":         { "concept": "The Absolute",            "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Silent Sentinel":           { "concept": "Duality",                 "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Witchblade":                { "concept": "Non-Duality",             "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Moonlit Anchor":            { "concept": "Paradox",                 "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Dream Vessel":              { "concept": "Entropy",                 "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Dark Crucible":             { "concept": "Information",             "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Defender of Order":         { "concept": "Complexity",              "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Just Warrior":              { "concept": "Emergence",               "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Zealous Crusader":          { "concept": "Evolution",               "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Stoic Guardian":            { "concept": "Quantum Entanglement",    "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Blooded Vessel":            { "concept": "Spacetime",               "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Iron Crucible":             { "concept": "Observer Effect",         "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Keeper of Lore":            { "concept": "Pattern",                 "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Wise Architect":            { "concept": "Self",                    "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Visionary Alchemist":       { "concept": "Ego",                     "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Tactical Herald":           { "concept": "Shadow (Jungian)",        "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Protean Guard":             { "concept": "Collective Unconscious",  "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Iron Messenger":            { "concept": "Anxiety",                 "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Fiery Magus":               { "concept": "Grief",                   "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Silent Scribe":             { "concept": "Trauma",                  "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Living Talisman":           { "concept": "Power",                   "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Secret Fire":               { "concept": "Network",                 "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Diplomatic Sage":           { "concept": "System",                  "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Charming Duelist":          { "concept": "AI (Artificial Intelligence)", "symbol": "Tree of Life", "thinker": "Carl Jung" },
  "The Artful Vessel":             { "concept": "Decentralization",        "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Cunning Mediator":          { "concept": "Order",                   "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Creative Trickster":        { "concept": "Chaos",                   "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Crucible Stone":            { "concept": "Being",                   "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Conquering Visionary":      { "concept": "Non-Being",               "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Steward of Plenty":         { "concept": "Existence",               "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Judicious Patriarch":       { "concept": "Consciousness",           "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Prophetic Flame":           { "concept": "Mind",                    "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Enlightened Monarch":       { "concept": "Matter",                  "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Sunlit Warrior":            { "concept": "Causality",               "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Philosopher‑King":          { "concept": "Time",                    "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Illuminated Vessel":        { "concept": "Space",                   "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Stoic Luminary":            { "concept": "Truth",                   "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Golden Alchemist":          { "concept": "Reality",                 "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Radiant Consort":           { "concept": "Illusion",                "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Guardian of Light":         { "concept": "Determinism",             "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Iron Sovereign":            { "concept": "The Absolute",            "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Fiery Crusader":            { "concept": "Duality",                 "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Visionary Herald":          { "concept": "Non-Duality",             "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Brilliant Strategist":      { "concept": "Paradox",                 "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Luminous Scribe":           { "concept": "Entropy",                 "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Disciplined Magician":      { "concept": "Information",             "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Radiant Transmuter":        { "concept": "Complexity",              "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Charismatic Magus":         { "concept": "Emergence",               "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Resolute Pillar":           { "concept": "Evolution",               "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Embodied Fire":             { "concept": "Quantum Entanglement",    "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Purifying Sun":             { "concept": "Spacetime",               "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Benevolent Ruler":          { "concept": "Observer Effect",         "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Passionate Hero":           { "concept": "Pattern",                 "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Loving Chalice":            { "concept": "Self",                    "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Tempered Lover":            { "concept": "Ego",                     "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Creative Catalyst":         { "concept": "Shadow (Jungian)",        "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Crusading Lover":           { "concept": "Collective Unconscious",  "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Harvest Maiden":            { "concept": "Anxiety",                 "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Gracious Matriarch":        { "concept": "Grief",                   "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Blooming Oracle":           { "concept": "Trauma",                  "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Heartbound Shield":         { "concept": "Power",                   "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Loyal Commander":           { "concept": "Network",                 "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Passion Spark":             { "concept": "System",                  "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Enduring Heart":            { "concept": "AI (Artificial Intelligence)", "symbol": "Ouroboros",   "thinker": "Plato" },
  "The Embodied Grace":            { "concept": "Decentralization",        "symbol": "Tree of Life",     "thinker": "Plato" },
  "The Tempered Flame":            { "concept": "Order",                   "symbol": "Ouroboros",        "thinker": "Carl Jung" },
  "The Pillar of Wisdom":          { "concept": "Chaos",                   "symbol": "Tree of Life",     "thinker": "Carl Jung" },
  "The Sacred Fountain":           { "concept": "Being",                   "symbol": "Ouroboros",        "thinker": "Plato" },
  "The Alchemical Judge":          { "concept": "Non-Being",               "symbol": "Tree of Life",     "thinker": "Plato" }
}; 